# NodeJs application for viewing result
apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    name: result-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: result-app
      image: kodekloud/examplevotingapp_result:v1 # specific image from course for demo
      ports:
        - containerPort: 80 # port that is used by our application