# NodePort for result app pod
apiVersion: v1
kind: Service
metadata:
  name: result-service # name is very important because it is direct link in our pods code http://result-service/
  labels:
    name: result-service
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  selector: # labels from pod
    name: result-app-pod
    app: demo-voting-app