# deployment for NodePort check
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort # type of service
  ports:
    - port: 80
      targetPort: 80 # pod port for access
      nodePort: 30004 # Node port for external access
  selector:
    app: myapp # selector should have label from pods/deployment/replicaset ect.

# 'kubectl creat -f .\nodeport-definition.yaml' , got to http://127.0.0.1:30004/ if you use minikube